name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    - name: Zip published files (correct root structure)
      run: |
        sudo apt-get update && sudo apt-get install -y zip
        cd publish
        zip -r ../function.zip * > /dev/null
        cd ..

    - name: Upload Publish ZIP (Optional Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: function-zip-artifact
        path: function.zip

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: function.zip